# -*- coding: UTF-8

import os

os.chdir("debug")

os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat01" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat02" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat03" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat04" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat05" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat06" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat10" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat13" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat16" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat19" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat20" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat21" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat22" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat23" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat24" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat28" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat31" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat32" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat33" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat34" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat35" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat36" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat40" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat43" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat44" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat45" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat46" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat47" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat48" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat52" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat55" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat58" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat59" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat60" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat61" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat62" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat63" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat67" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat70" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat71" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat72" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat73" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat74" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat75" + "\"")
os.system("monica-hermes.exe \"" + "C:/Users/nendel/development/nendel-data/AgMIP/wheat_heat_2_opt/wheat_heat79" + "\"")


os.chdir("..")
