// The reflection tier of the output table: an OId that names a *path* into
// MonicaModel instead of an id with a hand-written lambda behind it.
// See plan-reflective-outputs.md §§2.3-2.5.
//
// Three things live here:
//   - g_legacy_aliases, the legacy-name -> path table that keeps existing
//     sim.json files working while their values come from the new engine
//   - oid_bind_path, which compiles a path onto an OId at SETUP time
//   - resolve_oid_value, the daily read, which hands an open (unindexed)
//     dimension straight to get_complex_values so the layer-range and
//     layer-aggregation semantics are shared with the lambda tier rather
//     than forked.
package monica_io

import jx "../../support/jsonx"
import rp "../../support/reflectpath"
import tl "../../support/tools"
import core "../core"
import "core:fmt"

// A legacy output name's replacement: where the value lives, and the
// rounding/truncation that its lambda used to apply. `round`/`cast_to` are
// what make byte-identity possible - the CSV writer prints %.6g, so
// round(x, 3) and raw x are visibly different columns.
Alias :: struct {
	path:    string,
	round:   int, // -1 = do not round
	cast_to: OId_Cast,
	unit:    string, // only consulted for names build_output_table doesn't know
}

Alias_Entry :: struct {
	name:  string,
	alias: Alias,
}

// VERIFICATION TIER, read this before trusting a row: every entry here is
// checked by output_paths_test.odin to *compile* against Monica_Model and to
// land on a numeric leaf. Only the entries exercised by a fixture
// (odin/tests/diff_outputs.sh) are additionally verified to produce the same
// *value* the C++ does. A row that compiles is not a row that is right.
//
// Generated by `python odin/tools/gen_output_aliases.py` from
// src/io/build-output.cpp, then hand-audited. 125 of the C++'s 181 registered
// ids reduce to a path + rounding; the other 56 are genuinely computed and
// stay as lambdas in build_output.odin. Regenerate rather than hand-editing.
//
// Kept as a flat table, with the map built once on first use, for the same
// reason build_output_table is: a package-scope `map[...]{...}` literal
// allocates out of whatever context.allocator happens to be live at init.
g_alias_table := []Alias_Entry {
	{"AbBiom", {"currentCropModule.vc_AbovegroundBiomass", 1, .NONE, "kgDM ha-1"}},
	{"AbBiomNc", {"currentCropModule.vc_NConcentrationAbovegroundBiomass", 5, .NONE, "kgN ha-1"}},
	{"Act_ET", {"soilMoisture.vm_ActualEvapotranspiration", 1, .NONE, "mm"}},
	{"Act_Ev", {"soilMoisture.vm_ActualEvaporation", 1, .NONE, "mm"}},
	{"Act_Trans", {"currentCropModule.vc_ActualTranspiration", 1, .NONE, "mm"}},
	{"ActNup", {"currentCropModule.vc_TotalNUptake", 2, .NONE, "kgN ha-1"}},
	{"ActTraDef", {"currentCropModule.vc_ActualTranspirationDeficit", 2, .NONE, "0;1"}},
	{"AOM_Fast", {"soilColumn.layers.vo_AOM_Pool.0.vo_AOM_Fast", 5, .NONE, ""}},
	{"AOM_Slow", {"soilColumn.layers.vo_AOM_Pool.0.vo_AOM_Slow", 5, .NONE, ""}},
	{"Ass", {"currentCropModule.vc_Assimilates", 2, .NONE, "kgDM ha-1"}},
	{"AtmCO2", {"vw_AtmosphericCO2Concentration", 0, .NONE, "ppm"}},
	{"AtmO3", {"vw_AtmosphericO3Concentration", 0, .NONE, "ppb"}},
	{"BedGrad", {"soilMoisture.vc_PercentageSoilCoverage", 3, .NONE, "0;1"}},
	{"CapillaryRise", {"soilMoisture.vm_CapillaryWater", 3, .NONE, "mm"}},
	{"Carb", {"soilColumn.layers.vs_SoilCarbamid", 4, .NONE, "kgN m-3"}},
	{"Clay", {"soilColumn.layers.vs_SoilClayContent", 2, .NONE, "kg kg-1"}},
	{"CM-count", {"cultivationMethodCount", -1, .NONE, ""}},
	{"CN_Ratio_AOM_Fast", {"soilColumn.layers.vo_AOM_Pool.0.vo_CN_Ratio_AOM_Fast", 5, .NONE, ""}},
	{"CritN", {"currentCropModule.vc_CriticalNConcentration", 5, .NONE, "kgN ha-1"}},
	{"DaylF", {"currentCropModule.vc_DaylengthFactor", 2, .NONE, "0;1"}},
	{"ET0", {"soilMoisture.vm_ReferenceEvapotranspiration", 1, .NONE, "mm"}},
	{"Evaporated_from_surface", {"soilMoisture.vm_EvaporatedFromSurface", 1, .NONE, "mm"}},
	{"Evaporation", {"currentCropModule.vc_EvaporatedFromIntercept", 1, .NONE, "mm"}},
	{
		"Evaporation_from_intercept",
		{"currentCropModule.vc_EvaporatedFromIntercept", 1, .NONE, "mm"},
	},
	{"Evapotranspiration", {"currentCropModule.vc_RemainingEvapotranspiration", 1, .NONE, "mm"}},
	{"exportedCutBiomass", {"currentCropModule.vc_exportedCutBiomass", 1, .NONE, "kgDM ha-1"}},
	{"Fc", {"soilColumn.layers.vs_FieldCapacity", 4, .NONE, "m3 m-3"}},
	{"FrostD", {"soilMoisture.frostComponent.vm_FrostDepth", 1, .NONE, "m"}},
	{"FrostRed", {"currentCropModule.vc_CropFrostRedux", 2, .NONE, "0;1"}},
	{"Globrad", {"climateData.#last.globrad", 4, .NONE, ""}},
	{"GPP", {"currentCropModule.vc_GrossPrimaryProduction", 5, .NONE, "kgC ha-1"}},
	{"GroPhot", {"currentCropModule.vc_GrossPhotosynthesis", 4, .NONE, "kgCH2O ha-1"}},
	{"Groundw", {"vs_GroundwaterDepth", 2, .NONE, "m"}},
	{"GrowthR", {"currentCropModule.vc_GrowthRespirationAS", 4, .NONE, "kgCH2O ha-1"}},
	{
		"guenther-isoprene-emission",
		{"currentCropModule.guentherEmissions.isoprene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	{
		"guenther-monoterpene-emission",
		{
			"currentCropModule.guentherEmissions.monoterpene_emission",
			5,
			.NONE,
			"umol m-2Ground d-1",
		},
	},
	{"HeatRed", {"currentCropModule.vc_CropHeatRedux", 2, .NONE, "0;1"}},
	{"Height", {"currentCropModule.vc_CropHeight", 2, .NONE, "m"}},
	{"humusBalanceCarryOver", {"humusBalanceCarryOver", 1, .NONE, "Heq-NRW ha-1"}},
	{"IncFruit", {"currentCropModule.vc_OrganGrowthIncrement.3", 2, .NONE, "kg ha-1"}},
	{"IncLeaf", {"currentCropModule.vc_OrganGrowthIncrement.1", 2, .NONE, "kg ha-1"}},
	{"IncRoot", {"currentCropModule.vc_OrganGrowthIncrement.0", 2, .NONE, "kg ha-1"}},
	{"IncShoot", {"currentCropModule.vc_OrganGrowthIncrement.2", 2, .NONE, "kg ha-1"}},
	{"Infilt", {"soilMoisture.vm_Infiltration", 1, .NONE, "mm"}},
	{"Irrig", {"dailySumIrrigationWater", 3, .NONE, "mm"}},
	{
		"jjv-isoprene-emission",
		{"currentCropModule.jjvEmissions.isoprene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	{
		"jjv-monoterpene-emission",
		{"currentCropModule.jjvEmissions.monoterpene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	// {"Kc", {"soilMoisture.vc_KcFactor", 3, .NONE, ""}},
	{"Kcb", {"currentCropModule.vc_KcbFactor", 3, .NONE, ""}},
	{"Ke", {"soilMoisture.vm_Ke", 3, .NONE, ""}},
	{"LAI", {"currentCropModule.vc_LeafAreaIndex", 4, .NONE, "m2 m-2"}},
	{"LT50", {"currentCropModule.vc_LT50", 1, .NONE, "°C"}},
	{"MaintR", {"currentCropModule.vc_MaintenanceRespirationAS", 4, .NONE, "kgCH2O ha-1"}},
	{"Mois", {"soilMoisture.soil_column.layers.vs_SoilMoisture_m3", 3, .NONE, "m3 m-3"}},
	{"N2O", {"soilOrganic.vo_N2O_Produced", 5, .NONE, "kgN ha-1"}},
	{"N2Odenit", {"soilOrganic.vo_N2O_Produced_Denit", 5, .NONE, "kgN ha-1"}},
	{"N2Onit", {"soilOrganic.vo_N2O_Produced_Nit", 5, .NONE, "kgN ha-1"}},
	{"NDef", {"currentCropModule.vc_CropNRedux", 5, .NONE, "0;1"}},
	{"NEE", {"soilOrganic.vo_NetEcosystemExchange", 5, .NONE, "kgC ha-"}},
	{"NEP", {"soilOrganic.vo_NetEcosystemProduction", 5, .NONE, "kgC ha-1"}},
	{"NetPhot", {"currentCropModule.vc_NetPhotosynthesis", 2, .NONE, "kgCH2O ha-1"}},
	{"NFert", {"dailySumFertiliser", 1, .NONE, "kgN ha-1"}},
	{"NFixed", {"currentCropModule.vc_FixedN", 2, .NONE, "kgN ha-1"}},
	{"NH4", {"soilColumn.layers.vs_SoilNH4", 6, .NONE, "kgN m-3"}},
	{"NLeach", {"soilTransport.vq_LeachingAtBoundary", 3, .NONE, "kgN ha-1"}},
	{"NO2", {"soilColumn.layers.vs_SoilNO2", 6, .NONE, "kgN m-3"}},
	{"NO3", {"soilColumn.layers.vs_SoilNO3", 6, .NONE, "kgN m-3"}},
	{"NO3conv", {"soilTransport.vq_Convection", 8, .NONE, ""}},
	{"NO3disp", {"soilTransport.vq_Dispersion", 8, .NONE, ""}},
	{"noOfAOMPools", {"soilColumn.layers.0.vo_AOM_Pool.#len", -1, .INT, ""}},
	{"NOrgFert", {"dailySumOrgFertiliser", 1, .NONE, "kgN ha-1"}},
	{"NPP", {"currentCropModule.vc_NetPrimaryProduction", 5, .NONE, "kgC ha-1"}},
	{"O3-long-damage", {"currentCropModule.vc_O3_longTermDamage", 2, .NONE, "unitless"}},
	{"O3-short-damage", {"currentCropModule.vc_O3_shortTermDamage", 2, .NONE, "unitless"}},
	{"O3-total-uptake", {"currentCropModule.vc_O3_sumUptake", 2, .NONE, "�mol m-2"}},
	{"O3-WS-gs-reduction", {"currentCropModule.vc_O3_WStomatalClosure", 2, .NONE, "unitless"}},
	{"optCarbonExportedResidues", {"optCarbonExportedResidues", 1, .NONE, "kgDM ha-1"}},
	{"optCarbonReturnedResidues", {"optCarbonReturnedResidues", 1, .NONE, "kgDM ha-1"}},
	{"OxRed", {"currentCropModule.vc_OxygenDeficit", 2, .NONE, "0;1"}},
	{"PercolationRate", {"soilMoisture.vm_PercolationRate", 3, .NONE, "mm"}},
	{"pH", {"soilColumn.layers.vs_SoilpH", 2, .NONE, "kg kg-1"}},
	{"PotTraDef", {"currentCropModule.vc_PotentialTranspirationDeficit", 2, .NONE, "0;1"}},
	{"Precip", {"climateData.#last.precip", 4, .NONE, "mm"}},
	{"Pwp", {"soilColumn.layers.vs_PermanentWiltingPoint", 4, .NONE, "m3 m-3"}},
	{"Recharge", {"soilMoisture.vm_FluxAtLowerBoundary", 3, .NONE, "mm"}},
	{"RelDev", {"currentCropModule.vc_RelativeTotalDevelopment", 2, .NONE, "0;1"}},
	{"Relhumid", {"climateData.#last.relhumid", 4, .NONE, ""}},
	{"residueCutBiomass", {"currentCropModule.vc_residueCutBiomass", 1, .NONE, "kgDM ha-1"}},
	{"rootDensity", {"currentCropModule.vc_RootDensity", 4, .NONE, ""}},
	{"RootDep", {"currentCropModule.vc_RootingDepth", -1, .INT, "layer#"}},
	{"rootingZone", {"currentCropModule.vc_RootingZone", -1, .NONE, ""}},
	{"rootNConcentration", {"currentCropModule.vc_NConcentrationRoot", 4, .NONE, ""}},
	{"RootNDef", {"currentCropModule.rootNRedux", 2, .NONE, "0;1"}},
	{"RootWaUptak", {"currentCropModule.vc_Transpiration", 4, .NONE, "KgN ha-1"}},
	{"RunOff", {"soilMoisture.vm_SurfaceRunOff", 1, .NONE, "mm"}},
	{"Sand", {"soilColumn.layers.vs_SoilSandContent", 2, .NONE, "kg kg-1"}},
	{"Sat", {"soilColumn.layers.vs_Saturation", 4, .NONE, "m3 m-3"}},
	{"SnowD", {"soilMoisture.snowComponent.vm_SnowDepth", 1, .NONE, "mm"}},
	{"SoilpH", {"soilColumn.layers.0.vs_SoilpH", 1, .NONE, ""}},
	{"STemp", {"soilTemperature.soilColumn.layers.vs_SoilTemperature", 1, .NONE, "�C"}},
	{"StomRes", {"currentCropModule.vc_StomataResistance", 2, .NONE, "s m-1"}},
	{"Stone", {"soilColumn.layers.vs_SoilStoneContent", 2, .NONE, "kg kg-1"}},
	{
		"sumExportedCutBiomass",
		{"currentCropModule.vc_sumExportedCutBiomass", 1, .NONE, "kgDM ha-1"},
	},
	{"SumNFert", {"sumFertiliser", 1, .NONE, "kgN ha-1"}},
	{"SumNOrgFert", {"sumOrgFertiliser", 1, .NONE, "kgN ha-1"}},
	{"SumNUp", {"currentCropModule.vc_SumTotalNUptake", 2, .NONE, "kgN ha-1"}},
	{"sumResidueCutBiomass", {"currentCropModule.vc_sumResidueCutBiomass", 1, .NONE, "kgDM ha-1"}},
	{"Sunhours", {"climateData.#last.sunhours", 4, .NONE, ""}},
	{"Surface", {"soilMoisture.vm_SurfaceWaterStorage", 1, .NONE, "mm"}},
	{"SurfTemp", {"soilTemperature.soilSurfaceTemperature", 1, .NONE, "�C"}},
	{"Target", {"currentCropModule.vc_TargetNConcentration", 3, .NONE, "kgN ha-1"}},
	{"Tavg", {"climateData.#last.tavg", 4, .NONE, ""}},
	{"TempSum", {"currentCropModule.vc_CurrentTotalTemperatureSum", 1, .NONE, "�Cd"}},
	{"ThawD", {"soilMoisture.frostComponent.vm_ThawDepth", 1, .NONE, "m"}},
	{"TimeUnderAnoxia", {"currentCropModule.vc_TimeUnderAnoxia", 2, .NONE, "0;1"}},
	{"Tmax", {"climateData.#last.tmax", 4, .NONE, ""}},
	{"Tmin", {"climateData.#last.tmin", 4, .NONE, ""}},
	{"TotBiomN", {"currentCropModule.vc_TotalBiomassNContent", 1, .NONE, "kgN ha-1"}},
	{"Tra", {"currentCropModule.vc_ActualTranspiration", 2, .NONE, "mm"}},
	{"TraDef", {"currentCropModule.vc_TranspirationDeficit", 2, .NONE, "0;1"}},
	{"Transpiration", {"currentCropModule.vc_ActualTranspiration", 1, .NONE, "mm"}},
	{"TraRed", {"currentCropModule.vc_TranspirationReduced", 2, .NONE, "mm"}},
	{"VernF", {"currentCropModule.vc_VernalisationFactor", 2, .NONE, "0;1"}},
	{"WaterFlux", {"soilMoisture.vm_WaterFlux", 1, .NONE, "mm/d"}},
	{"Wind", {"climateData.#last.wind", 4, .NONE, ""}},
}

// NOT aliased, deliberately - the computed tier (plan-reflective-outputs.md
// §1). A path cannot express any of these, and faking one would be a silently
// wrong column rather than a missing one:
//
//   Date/DOY/Month/Year/days-since-start
//                 Date's year()/month()/dayOfYear()/toIsoDateString() are
//                 procs, not fields
//   Crop          a string built from the crop params
//   Stage         vc_DevelopmentalStage + 1
//   Count         the literal 1
//   ETa/ETc, Pot_ET, WaterContent, AWC, SOC-X-Y, PASW, Tmax>=40
//                 arithmetic over two or more fields
//   Yield, SecondaryYield, SOC, N, Nmin, NetNmin, Denit, Rh, NH3, Silt,
//   EffRootDep, AbBiomN, YieldN, YieldNc, Protein, GrainN, Nresid, Nstress,
//   PotNup, Ra, LightInterception1/2, ActNupLayer
//                 proc calls
//   OrgBiom, OrgGreenBiom, NPP-Organs, Ra-Organs
//                 guarded by speciesParams' organ COUNT, not by the array
//                 bound, so an out-of-range organ must read 0.0 even when the
//                 array has an element there
//   OrgN, Co, AOMf, AOMs, SMBf, SMBs, SOMf, SOMs, CBal, SMB-CO2-ER,
//   actammoxrate, actnitrate, actdenitrate
//                 these clamp fromLayer/toLayer to numberOfOrganicLayers()-1
//                 before aggregating, so a range past the organic layers
//                 repeats the last organic layer's value where reflection
//                 would report *missing* -> 0.0. Different numbers, not just
//                 a different route to them.

@(private)
g_legacy_aliases: map[string]Alias
@(private)
g_legacy_aliases_built: bool

legacy_aliases :: proc(allocator := context.allocator) -> ^map[string]Alias {
	if !g_legacy_aliases_built {
		g_legacy_aliases = make(map[string]Alias, len(g_alias_table), allocator)
		for e in g_alias_table {
			g_legacy_aliases[e.name] = e.alias
		}
		g_legacy_aliases_built = true
	}
	return &g_legacy_aliases
}

// A/B bisection escape hatch (sim.json: output."use-legacy-output-fns?").
// When true, parse_output_ids consults build_output_table before the alias
// table, i.e. the pre-reflection behaviour, so a moved CSV column can be
// pinned to the engine rather than to anything else in the same commit.
g_use_legacy_output_fns: bool

// The model as an `any` for the path engine. Built explicitly rather than by
// letting `model^` coerce: Monica_Model is large, and this makes it obvious
// that no copy happens and that resolve() writes through to the real fields.
@(private)
model_root :: proc(model: ^core.Monica_Model) -> any {
	return any{rawptr(model), typeid_of(core.Monica_Model)}
}

// Compiles `path` onto `oid` at setup time. The plan is heap-allocated in
// `allocator` (the run's arena) because OId is copied by value everywhere.
oid_bind_path :: proc(
	oid: ^OId,
	path: string,
	allocator := context.allocator,
) -> rp.Compile_Error {
	plan, err := rp.compile(typeid_of(core.Monica_Model), path, allocator)
	if rp.failed(err) {
		return err
	}
	p := new(rp.Path_Plan, allocator)
	p^ = plan
	oid.path = p.src
	oid.plan = p
	return rp.Compile_Error{}
}

// The daily read for a reflection-backed oid - the counterpart of
// `ofs[oid.id](model, oid)`.
//
// An open dimension goes through get_complex_values, which is the same
// procedure the layer-based lambdas (Mois/SOC/N) use, so fromLayer/toLayer/
// organ/layerAggOp behave identically on both tiers. Note the asymmetry that
// buys byte-identity: get_complex_values rounds each element of an
// unaggregated range but does NOT round an aggregated one, exactly as the
// C++ does.
resolve_oid_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	allocator := context.allocator,
) -> jx.Value {
	if oid.plan.open_step >= 0 {
		return get_complex_values(model, oid, nil, oid.roundToDigits, allocator)
	}

	// A missing value - nil currentCropModule, unset Maybe, absent map key -
	// yields 0.0, matching every legacy lambda's `... ? ... : 0.0` ternary.
	v, ok := rp.resolve_f64(oid.plan, model_root(model))
	if !ok {
		v = 0.0
	}
	if oid.castTo == .INT {
		return jx.i(int(v))
	}
	return jx.f(round_or_not(v, oid.roundToDigits))
}

// ---------------------------------------------------------------------------
// the tier-agnostic read/write entry points
// ---------------------------------------------------------------------------
//
// Everything that reads or writes an oid goes through these two, so a caller
// never has to know whether the oid is lambda-backed or path-backed:
// store_results, the SetValue workstep, and the primitive-calc expression
// operands all just ask.

// Is there any way to read this oid?
@(require_results)
oid_has_getter :: proc(oid: OId) -> bool {
	if oid.plan != nil {
		return true
	}
	_, ok := build_output_table().ofs[oid.id]
	return ok
}

// C++: `ofs[oid.id](monica, oid)`, widened by the path tier.
oid_get_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	allocator := context.allocator,
) -> (
	jx.Value,
	bool,
) {
	if oid.plan != nil {
		return resolve_oid_value(model, oid, allocator), true
	}
	if of, ok := build_output_table().ofs[oid.id]; ok {
		return of(model, oid), true
	}
	return jx.Value{}, false
}

// Is there any way to WRITE this oid?
//
// The path tier is what makes this interesting. Before it, exactly two of the
// C++'s 181 ids had a registered setf (Stage and Mois) - deliberately, but it
// means a model state that no one thought to expose was simply unreachable
// from a SetValue workstep. Any path-backed oid whose leaf is a real,
// writable number now is.
@(require_results)
oid_has_setter :: proc(oid: OId) -> bool {
	if oid.plan != nil && rp.is_writable(oid.plan) {
		return true
	}
	_, ok := build_output_table().setfs[oid.id]
	return ok
}

// C++: `setfs[oid.id](monica, oid, value)`, widened by the path tier.
//
// The path tier is tried FIRST, mirroring the read side's tier order
// (§2.5) so that a name cannot read through one tier and write through the
// other. That is safe for the two ids where both exist: `Mois`' C++ setf is a
// bare assignment to the same field its alias points at, and `Stage` - whose
// setf is *not* a bare assignment - has no alias row at all, because it is in
// the computed tier.
//
// Returns false when nothing was written, which is a real outcome and not
// just an error: a path through a nil `currentCropModule`, or an out-of-range
// layer, resolves to *missing*, and the C++ ternaries this mirrors skip the
// write too.
oid_set_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	value: jx.Value,
	allocator := context.allocator,
) -> bool {
	if oid.plan != nil && rp.is_writable(oid.plan) {
		if oid.plan.open_step >= 0 {
			// the layer/organ range and the scalar-fills-every-layer rule are
			// set_complex_values', exactly as on the read side
			set_complex_values(model, oid, nil, value, allocator)
			return true
		}
		v, ok := json_to_f64(value)
		if !ok {
			return false
		}
		return rp.write_f64_at(oid.plan, model_root(model), v)
	}
	if setf, ok := build_output_table().setfs[oid.id]; ok {
		setf(model, oid, value)
		return true
	}
	return false
}

// The value side of a write. Numbers are numbers; a JSON bool is accepted as
// 1/0 so a bool-typed model field can be set the obvious way. Anything else -
// a string, an object, null - is not a write.
@(private)
json_to_f64 :: proc(value: jx.Value) -> (f64, bool) {
	if jx.is_number(value) {
		return jx.number_value(value), true
	}
	if jx.is_bool(value) {
		return jx.bool_value_of(value) ? 1 : 0, true
	}
	return 0, false
}

// The per-index write set_complex_values delegates to for a path-backed oid,
// the counterpart of the resolve_f64 call on the read side.
@(private)
set_plan_value_at :: proc(model: ^core.Monica_Model, oid: OId, i: int, value: jx.Value) {
	v, ok := json_to_f64(value)
	if !ok {
		return
	}
	rp.write_f64_at(oid.plan, model_root(model), v, i)
}

// tools.round(v, -1) rounds to TENS (the C++ round_to_digits takes a signed
// digit count and means it), so "do not round" needs its own branch rather
// than a sentinel passed through.
@(private)
round_or_not :: proc(v: f64, digits: int) -> f64 {
	if digits < 0 {
		return v
	}
	return tl.round(v, digits)
}

// Setup-time diagnostics. Reported once, with the offending spec - not once
// per day for 2,500 days.
@(private)
warn_bad_path :: proc(name: string, err: rp.Compile_Error) {
	fmt.eprintfln(
		"parse_output_ids: ignoring output %q - %s%s%s",
		name,
		err.msg,
		err.at == "" ? "" : " at segment ",
		err.at,
	)
}
