// The reflection tier of the output table: an OId that names a *path* into
// MonicaModel instead of an id with a hand-written lambda behind it.
// See plan-reflective-outputs.md §§2.3-2.5.
//
// Three things live here:
//   - g_legacy_aliases, the legacy-name -> path table that keeps existing
//     sim.json files working while their values come from the new engine
//   - oid_bind_path, which compiles a path onto an OId at SETUP time
//   - resolve_oid_value, the daily read, which hands an open (unindexed)
//     dimension straight to get_complex_values so the layer-range and
//     layer-aggregation semantics are shared with the lambda tier rather
//     than forked.
package monica_io

import jx "../../support/jsonx"
import rp "../../support/reflectpath"
import tl "../../support/tools"
import core "../core"
import "core:fmt"

// A legacy output name's replacement: where the value lives, and the
// rounding/truncation that its lambda used to apply. `round`/`cast_to` are
// what make byte-identity possible - the CSV writer prints %.6g, so
// round(x, 3) and raw x are visibly different columns.
Alias :: struct {
	path:    string,
	round:   int, // -1 = do not round
	cast_to: OId_Cast,
	unit:    string, // only consulted for names build_output_table doesn't know
}

Alias_Entry :: struct {
	name:  string,
	alias: Alias,
}

// VERIFICATION TIER, read this before trusting a row: every entry here is
// checked by output_paths_test.odin to *compile* against Monica_Model and to
// land on a numeric leaf. Only the entries exercised by a fixture
// (odin/tests/diff_outputs.sh) are additionally verified to produce the same
// *value* the C++ does. A row that compiles is not a row that is right.
//
// Generated by `python odin/tools/gen_output_aliases.py` from
// src/io/build-output.cpp, then hand-audited. 125 of the C++'s 181 registered
// ids reduce to a path + rounding; the other 56 are genuinely computed and
// stay as lambdas in build_output.odin. Regenerate rather than hand-editing.
//
// Kept as a flat table, with the map built once on first use, for the same
// reason build_output_table is: a package-scope `map[...]{...}` literal
// allocates out of whatever context.allocator happens to be live at init.
g_alias_table := []Alias_Entry {
	{"AbBiom", {"current_crop_module.aboveground_biomass", 1, .NONE, "kgDM ha-1"}},
	{"AbBiomNc", {"current_crop_module.n_concentration_aboveground_biomass", 5, .NONE, "kgN ha-1"}},
	{"Act_ET", {"soil_moisture.actual_evapotranspiration", 1, .NONE, "mm"}},
	{"Act_Ev", {"soil_moisture.actual_evaporation", 1, .NONE, "mm"}},
	{"Act_Trans", {"current_crop_module.actual_transpiration", 1, .NONE, "mm"}},
	{"ActNup", {"current_crop_module.total_n_uptake", 2, .NONE, "kgN ha-1"}},
	{"ActTraDef", {"current_crop_module.actual_transpiration_deficit", 2, .NONE, "0;1"}},
	{"AOM_Fast", {"soil_column.layers.vo_AOM_Pool.0.aom_fast", 5, .NONE, ""}},
	{"AOM_Slow", {"soil_column.layers.vo_AOM_Pool.0.aom_slow", 5, .NONE, ""}},
	{"Ass", {"current_crop_module.assimilates", 2, .NONE, "kgDM ha-1"}},
	{"AtmCO2", {"vw_atmospheric_co2_concentration", 0, .NONE, "ppm"}},
	{"AtmO3", {"vw_atmospheric_o3_concentration", 0, .NONE, "ppb"}},
	{"BedGrad", {"soil_moisture.soil_coverage_percent", 3, .NONE, "0;1"}},
	{"CapillaryRise", {"soil_moisture.capillary_water", 3, .NONE, "mm"}},
	{"Carb", {"soil_column.layers.soil_carbamid", 4, .NONE, "kgN m-3"}},
	{"Clay", {"soil_column.layers.soil_clay_content", 2, .NONE, "kg kg-1"}},
	{"CM-count", {"cultivation_method_count", -1, .NONE, ""}},
	{"CN_Ratio_AOM_Fast", {"soil_column.layers.vo_AOM_Pool.0.cn_ratio_aom_fast", 5, .NONE, ""}},
	{"CritN", {"current_crop_module.critical_n_concentration", 5, .NONE, "kgN ha-1"}},
	{"DaylF", {"current_crop_module.daylength_factor", 2, .NONE, "0;1"}},
	{"ET0", {"soil_moisture.reference_evapotranspiration", 1, .NONE, "mm"}},
	{"Evaporated_from_surface", {"soil_moisture.evaporated_from_surface", 1, .NONE, "mm"}},
	{"Evaporation", {"current_crop_module.evaporated_from_intercept", 1, .NONE, "mm"}},
	{
		"Evaporation_from_intercept",
		{"current_crop_module.evaporated_from_intercept", 1, .NONE, "mm"},
	},
	{"Evapotranspiration", {"current_crop_module.remaining_evapotranspiration", 1, .NONE, "mm"}},
	{"exportedCutBiomass", {"current_crop_module.exported_cut_biomass", 1, .NONE, "kgDM ha-1"}},
	{"Fc", {"soil_column.layers.field_capacity", 4, .NONE, "m3 m-3"}},
	{"FrostD", {"soil_moisture.frost_component.frost_depth", 1, .NONE, "m"}},
	{"FrostRed", {"current_crop_module.crop_frost_redux", 2, .NONE, "0;1"}},
	{"Globrad", {"climate_data.#last.globrad", 4, .NONE, ""}},
	{"GPP", {"current_crop_module.gross_primary_production", 5, .NONE, "kgC ha-1"}},
	{"GroPhot", {"current_crop_module.gross_photosynthesis", 4, .NONE, "kgCH2O ha-1"}},
	{"Groundw", {"vs_groundwater_depth", 2, .NONE, "m"}},
	{"GrowthR", {"current_crop_module.growth_respiration_as", 4, .NONE, "kgCH2O ha-1"}},
	{
		"guenther-isoprene-emission",
		{"current_crop_module.guenther_emissions.isoprene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	{
		"guenther-monoterpene-emission",
		{
			"current_crop_module.guenther_emissions.monoterpene_emission",
			5,
			.NONE,
			"umol m-2Ground d-1",
		},
	},
	{"HeatRed", {"current_crop_module.crop_heat_redux", 2, .NONE, "0;1"}},
	{"Height", {"current_crop_module.crop_height", 2, .NONE, "m"}},
	{"humus_balance_carry_over", {"humus_balance_carry_over", 1, .NONE, "Heq-NRW ha-1"}},
	{"IncFruit", {"current_crop_module.organ_growth_increment.3", 2, .NONE, "kg ha-1"}},
	{"IncLeaf", {"current_crop_module.organ_growth_increment.1", 2, .NONE, "kg ha-1"}},
	{"IncRoot", {"current_crop_module.organ_growth_increment.0", 2, .NONE, "kg ha-1"}},
	{"IncShoot", {"current_crop_module.organ_growth_increment.2", 2, .NONE, "kg ha-1"}},
	{"Infilt", {"soil_moisture.infiltration", 1, .NONE, "mm"}},
	{"Irrig", {"daily_sum_irrigation_water", 3, .NONE, "mm"}},
	{
		"jjv-isoprene-emission",
		{"current_crop_module.jjv_emissions.isoprene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	{
		"jjv-monoterpene-emission",
		{"current_crop_module.jjv_emissions.monoterpene_emission", 5, .NONE, "umol m-2Ground d-1"},
	},
	{"Kc", {"soil_moisture.kc_factor", 3, .NONE, ""}},
	{"Kcb", {"current_crop_module.kcb_factor", 3, .NONE, ""}},
	{"Ke", {"soil_moisture.ke", 3, .NONE, ""}},
	{"LAI", {"current_crop_module.leaf_area_index", 4, .NONE, "m2 m-2"}},
	{"LT50", {"current_crop_module.lt50", 1, .NONE, "°C"}},
	{"MaintR", {"current_crop_module.maintenance_respiration_as", 4, .NONE, "kgCH2O ha-1"}},
	{"Mois", {"soil_moisture.soil_column.layers.soil_moisture_m3", 3, .NONE, "m3 m-3"}},
	{"N2O", {"soil_organic.n2o_produced", 5, .NONE, "kgN ha-1"}},
	{"N2Odenit", {"soil_organic.n2o_produced_denit", 5, .NONE, "kgN ha-1"}},
	{"N2Onit", {"soil_organic.n2o_produced_nit", 5, .NONE, "kgN ha-1"}},
	{"NDef", {"current_crop_module.crop_n_redux", 5, .NONE, "0;1"}},
	{"NEE", {"soil_organic.net_ecosystem_exchange", 5, .NONE, "kgC ha-"}},
	{"NEP", {"soil_organic.net_ecosystem_production", 5, .NONE, "kgC ha-1"}},
	{"NetPhot", {"current_crop_module.net_photosynthesis", 2, .NONE, "kgCH2O ha-1"}},
	{"NFert", {"daily_sum_fertiliser", 1, .NONE, "kgN ha-1"}},
	{"NFixed", {"current_crop_module.fixed_n", 2, .NONE, "kgN ha-1"}},
	{"NH4", {"soil_column.layers.soil_nh4", 6, .NONE, "kgN m-3"}},
	{"NLeach", {"soil_transport.leaching_at_boundary", 3, .NONE, "kgN ha-1"}},
	{"NO2", {"soil_column.layers.soil_no2", 6, .NONE, "kgN m-3"}},
	{"NO3", {"soil_column.layers.soil_no3", 6, .NONE, "kgN m-3"}},
	{"NO3conv", {"soil_transport.convection", 8, .NONE, ""}},
	{"NO3disp", {"soil_transport.dispersion", 8, .NONE, ""}},
	{"noOfAOMPools", {"soil_column.layers.0.vo_AOM_Pool.#len", -1, .INT, ""}},
	{"NOrgFert", {"daily_sum_org_fertiliser", 1, .NONE, "kgN ha-1"}},
	{"NPP", {"current_crop_module.net_primary_production", 5, .NONE, "kgC ha-1"}},
	{"O3-long-damage", {"current_crop_module.o3_long_term_damage", 2, .NONE, "unitless"}},
	{"O3-short-damage", {"current_crop_module.o3_short_term_damage", 2, .NONE, "unitless"}},
	{"O3-total-uptake", {"current_crop_module.o3_sum_uptake", 2, .NONE, "�mol m-2"}},
	{"O3-WS-gs-reduction", {"current_crop_module.o3_w_stomatal_closure", 2, .NONE, "unitless"}},
	{"opt_carbon_exported_residues", {"opt_carbon_exported_residues", 1, .NONE, "kgDM ha-1"}},
	{"opt_carbon_returned_residues", {"opt_carbon_returned_residues", 1, .NONE, "kgDM ha-1"}},
	{"OxRed", {"current_crop_module.oxygen_deficit", 2, .NONE, "0;1"}},
	{"PercolationRate", {"soil_moisture.percolation_rate", 3, .NONE, "mm"}},
	{"pH", {"soil_column.layers.soil_ph", 2, .NONE, "kg kg-1"}},
	{"PotTraDef", {"current_crop_module.potential_transpiration_deficit", 2, .NONE, "0;1"}},
	{"Precip", {"climate_data.#last.precip", 4, .NONE, "mm"}},
	{"Pwp", {"soil_column.layers.permanent_wilting_point", 4, .NONE, "m3 m-3"}},
	{"Recharge", {"soil_column.vs_FluxAtLowerBoundary", 3, .NONE, "mm"}},
	{"RelDev", {"current_crop_module.relative_total_development", 2, .NONE, "0;1"}},
	{"Relhumid", {"climate_data.#last.relhumid", 4, .NONE, ""}},
	{"residueCutBiomass", {"current_crop_module.residue_cut_biomass", 1, .NONE, "kgDM ha-1"}},
	{"rootDensity", {"current_crop_module.root_density", 4, .NONE, ""}},
	{"RootDep", {"current_crop_module.rooting_depth", -1, .INT, "layer#"}},
	{"rootingZone", {"current_crop_module.rooting_zone", -1, .NONE, ""}},
	{"rootNConcentration", {"current_crop_module.n_concentration_root", 4, .NONE, ""}},
	{"RootNDef", {"current_crop_module.root_n_redux", 2, .NONE, "0;1"}},
	{"RootWaUptak", {"current_crop_module.transpiration", 4, .NONE, "KgN ha-1"}},
	{"RunOff", {"soil_moisture.surface_run_off", 1, .NONE, "mm"}},
	{"Sand", {"soil_column.layers.soil_sand_content", 2, .NONE, "kg kg-1"}},
	{"Sat", {"soil_column.layers.saturation", 4, .NONE, "m3 m-3"}},
	{"SnowD", {"soil_moisture.snow_component.snow_depth", 1, .NONE, "mm"}},
	{"SoilpH", {"soil_column.layers.0.soil_ph", 1, .NONE, ""}},
	{"STemp", {"soil_temperature.soil_column.layers.soil_temperature", 1, .NONE, "°C"}},
	{"StomRes", {"current_crop_module.stomata_resistance", 2, .NONE, "s m-1"}},
	{"Stone", {"soil_column.layers.soil_stone_content", 2, .NONE, "kg kg-1"}},
	{
		"sumExportedCutBiomass",
		{"current_crop_module.sum_exported_cut_biomass", 1, .NONE, "kgDM ha-1"},
	},
	{"SumNFert", {"sum_fertiliser", 1, .NONE, "kgN ha-1"}},
	{"SumNOrgFert", {"sum_org_fertiliser", 1, .NONE, "kgN ha-1"}},
	{"SumNUp", {"current_crop_module.sum_total_n_uptake", 2, .NONE, "kgN ha-1"}},
	{"sumResidueCutBiomass", {"current_crop_module.sum_residue_cut_biomass", 1, .NONE, "kgDM ha-1"}},
	{"Sunhours", {"climate_data.#last.sunhours", 4, .NONE, ""}},
	{"Surface", {"soil_column.vs_SurfaceWaterStorage", 1, .NONE, "mm"}},
	{"SurfTemp", {"soil_temperature.soil_surface_temperature", 1, .NONE, "�C"}},
	{"Target", {"current_crop_module.target_n_concentration", 3, .NONE, "kgN ha-1"}},
	{"Tavg", {"climate_data.#last.tavg", 4, .NONE, ""}},
	{"TempSum", {"current_crop_module.current_total_temperature_sum", 1, .NONE, "�Cd"}},
	{"ThawD", {"soil_moisture.frost_component.thaw_depth", 1, .NONE, "m"}},
	{"TimeUnderAnoxia", {"current_crop_module.time_under_anoxia", 2, .NONE, "0;1"}},
	{"Tmax", {"climate_data.#last.tmax", 4, .NONE, ""}},
	{"Tmin", {"climate_data.#last.tmin", 4, .NONE, ""}},
	{"TotBiomN", {"current_crop_module.total_biomass_n_content", 1, .NONE, "kgN ha-1"}},
	{"Tra", {"current_crop_module.actual_transpiration", 2, .NONE, "mm"}},
	{"TraDef", {"current_crop_module.transpiration_deficit", 2, .NONE, "0;1"}},
	{"Transpiration", {"current_crop_module.actual_transpiration", 1, .NONE, "mm"}},
	{"TraRed", {"current_crop_module.transpiration_reduced", 2, .NONE, "mm"}},
	{"VernF", {"current_crop_module.vernalisation_factor", 2, .NONE, "0;1"}},
	{"WaterFlux", {"soil_column.layers.soil_water_flux", 1, .NONE, "mm/d"}},
	{"Wind", {"climate_data.#last.wind", 4, .NONE, ""}},
}

// NOT aliased, deliberately - the computed tier (plan-reflective-outputs.md
// §1). A path cannot express any of these, and faking one would be a silently
// wrong column rather than a missing one:
//
//   Date/DOY/Month/Year/days-since-start
//                 Date's year()/month()/dayOfYear()/toIsoDateString() are
//                 procs, not fields
//   Crop          a string built from the crop params
//   Stage         vc_DevelopmentalStage + 1
//   Count         the literal 1
//   ETa/ETc, Pot_ET, WaterContent, AWC, SOC-X-Y, PASW, Tmax>=40
//                 arithmetic over two or more fields
//   Yield, SecondaryYield, SOC, N, Nmin, NetNmin, Denit, Rh, NH3, Silt,
//   EffRootDep, AbBiomN, YieldN, YieldNc, Protein, GrainN, Nresid, Nstress,
//   PotNup, Ra, LightInterception1/2, ActNupLayer
//                 proc calls
//   OrgBiom, OrgGreenBiom, NPP-Organs, Ra-Organs
//                 guarded by speciesParams' organ COUNT, not by the array
//                 bound, so an out-of-range organ must read 0.0 even when the
//                 array has an element there
//   OrgN, Co, AOMf, AOMs, SMBf, SMBs, SOMf, SOMs, CBal, SMB-CO2-ER,
//   actammoxrate, actnitrate, actdenitrate
//                 these clamp fromLayer/toLayer to numberOfOrganicLayers()-1
//                 before aggregating, so a range past the organic layers
//                 repeats the last organic layer's value where reflection
//                 would report *missing* -> 0.0. Different numbers, not just
//                 a different route to them.

@(private)
g_legacy_aliases: map[string]Alias
@(private)
g_legacy_aliases_built: bool

legacy_aliases :: proc(allocator := context.allocator) -> ^map[string]Alias {
	if !g_legacy_aliases_built {
		// Built once and read for the rest of the process, so NOT from `allocator`
		// (one request's arena, in a server) - see tools.process_cache_allocator.
		// Its contents are all static-table literals, so nothing here depends on
		// the caller's data.
		g_legacy_aliases = make(map[string]Alias, len(g_alias_table), tl.process_cache_allocator())
		for e in g_alias_table {
			g_legacy_aliases[e.name] = e.alias
		}
		g_legacy_aliases_built = true
	}
	return &g_legacy_aliases
}

// A/B bisection escape hatch (sim.json: output."use-legacy-output-fns?").
// When true, parse_output_ids consults build_output_table before the alias
// table, i.e. the pre-reflection behaviour, so a moved CSV column can be
// pinned to the engine rather than to anything else in the same commit.
g_use_legacy_output_fns: bool

// The model as an `any` for the path engine. Built explicitly rather than by
// letting `model^` coerce: Monica_Model is large, and this makes it obvious
// that no copy happens and that resolve() writes through to the real fields.
@(private)
model_root :: proc(model: ^core.Monica_Model) -> any {
	return any{rawptr(model), typeid_of(core.Monica_Model)}
}

// Compiles `path` onto `oid` at setup time. The plan is heap-allocated in
// `allocator` (the run's arena) because OId is copied by value everywhere.
oid_bind_path :: proc(
	oid: ^OId,
	path: string,
	allocator := context.allocator,
) -> rp.Compile_Error {
	plan, err := rp.compile(typeid_of(core.Monica_Model), path, allocator)
	if rp.failed(err) {
		return err
	}
	p := new(rp.Path_Plan, allocator)
	p^ = plan
	oid.path = p.src
	oid.plan = p
	return rp.Compile_Error{}
}

// The daily read for a reflection-backed oid - the counterpart of
// `ofs[oid.id](model, oid)`.
//
// An open dimension goes through get_complex_values, which is the same
// procedure the layer-based lambdas (Mois/SOC/N) use, so fromLayer/toLayer/
// organ/layerAggOp behave identically on both tiers. Note the asymmetry that
// buys byte-identity: get_complex_values rounds each element of an
// unaggregated range but does NOT round an aggregated one, exactly as the
// C++ does.
resolve_oid_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	allocator := context.allocator,
) -> jx.Value {
	if oid.plan.open_step >= 0 {
		return get_complex_values(model, oid, nil, oid.roundToDigits, allocator)
	}

	// A missing value - nil currentCropModule, unset Maybe, absent map key -
	// yields 0.0, matching every legacy lambda's `... ? ... : 0.0` ternary.
	v, ok := rp.resolve_f64(oid.plan, model_root(model))
	if !ok {
		v = 0.0
	}
	if oid.castTo == .INT {
		return jx.i(int(v))
	}
	return jx.f(round_or_not(v, oid.roundToDigits))
}

// ---------------------------------------------------------------------------
// the tier-agnostic read/write entry points
// ---------------------------------------------------------------------------
//
// Everything that reads or writes an oid goes through these two, so a caller
// never has to know whether the oid is lambda-backed or path-backed:
// store_results, the SetValue workstep, and the primitive-calc expression
// operands all just ask.

// Is there any way to read this oid?
@(require_results)
oid_has_getter :: proc(oid: OId) -> bool {
	if oid.plan != nil {
		return true
	}
	_, ok := build_output_table().ofs[oid.id]
	return ok
}

// C++: `ofs[oid.id](monica, oid)`, widened by the path tier.
oid_get_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	allocator := context.allocator,
) -> (
	jx.Value,
	bool,
) {
	if oid.plan != nil {
		return resolve_oid_value(model, oid, allocator), true
	}
	if of, ok := build_output_table().ofs[oid.id]; ok {
		return of(model, oid), true
	}
	return jx.Value{}, false
}

// Is there any way to WRITE this oid?
//
// The path tier is what makes this interesting. Before it, exactly two of the
// C++'s 181 ids had a registered setf (Stage and Mois) - deliberately, but it
// means a model state that no one thought to expose was simply unreachable
// from a SetValue workstep. Any path-backed oid whose leaf is a real,
// writable number now is.
@(require_results)
oid_has_setter :: proc(oid: OId) -> bool {
	if oid.plan != nil && rp.is_writable(oid.plan) {
		return true
	}
	_, ok := build_output_table().setfs[oid.id]
	return ok
}

// C++: `setfs[oid.id](monica, oid, value)`, widened by the path tier.
//
// The path tier is tried FIRST, mirroring the read side's tier order
// (§2.5) so that a name cannot read through one tier and write through the
// other. That is safe for the two ids where both exist: `Mois`' C++ setf is a
// bare assignment to the same field its alias points at, and `Stage` - whose
// setf is *not* a bare assignment - has no alias row at all, because it is in
// the computed tier.
//
// Returns false when nothing was written, which is a real outcome and not
// just an error: a path through a nil `currentCropModule`, or an out-of-range
// layer, resolves to *missing*, and the C++ ternaries this mirrors skip the
// write too.
oid_set_value :: proc(
	model: ^core.Monica_Model,
	oid: OId,
	value: jx.Value,
	allocator := context.allocator,
) -> bool {
	if oid.plan != nil && rp.is_writable(oid.plan) {
		if oid.plan.open_step >= 0 {
			// the layer/organ range and the scalar-fills-every-layer rule are
			// set_complex_values', exactly as on the read side
			set_complex_values(model, oid, nil, value, allocator)
			return true
		}
		v, ok := json_to_f64(value)
		if !ok {
			return false
		}
		return rp.write_f64_at(oid.plan, model_root(model), v)
	}
	if setf, ok := build_output_table().setfs[oid.id]; ok {
		setf(model, oid, value)
		return true
	}
	return false
}

// The value side of a write. Numbers are numbers; a JSON bool is accepted as
// 1/0 so a bool-typed model field can be set the obvious way. Anything else -
// a string, an object, null - is not a write.
@(private)
json_to_f64 :: proc(value: jx.Value) -> (f64, bool) {
	if jx.is_number(value) {
		return jx.number_value(value), true
	}
	if jx.is_bool(value) {
		return jx.bool_value_of(value) ? 1 : 0, true
	}
	return 0, false
}

// The per-index write set_complex_values delegates to for a path-backed oid,
// the counterpart of the resolve_f64 call on the read side.
@(private)
set_plan_value_at :: proc(model: ^core.Monica_Model, oid: OId, i: int, value: jx.Value) {
	v, ok := json_to_f64(value)
	if !ok {
		return
	}
	rp.write_f64_at(oid.plan, model_root(model), v, i)
}

// tools.round(v, -1) rounds to TENS (the C++ round_to_digits takes a signed
// digit count and means it), so "do not round" needs its own branch rather
// than a sentinel passed through.
@(private)
round_or_not :: proc(v: f64, digits: int) -> f64 {
	if digits < 0 {
		return v
	}
	return tl.round(v, digits)
}

// Setup-time diagnostics. Reported once, with the offending spec - not once
// per day for 2,500 days.
@(private)
warn_bad_path :: proc(name: string, err: rp.Compile_Error) {
	fmt.eprintfln(
		"parse_output_ids: ignoring output %q - %s%s%s",
		name,
		err.msg,
		err.at == "" ? "" : " at segment ",
		err.at,
	)
}
